# Generated by Django 4.2.7 on 2024-01-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_notify',
            field=models.BooleanField(default=True, verbose_name='通知する'),
        ),
    ]
