# Generated by Django 4.2.7 on 2024-01-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_notifycategory_article_good_notify_category'),
        ('users', '0003_customuser_is_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_notify',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_not_notify',
            field=models.ManyToManyField(blank=True, to='blog.notifycategory', verbose_name='通知しないカテゴリ'),
        ),
    ]
