# Generated by Django 4.2.7 on 2023-12-26 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通報した日時')),
                ('reason', models.CharField(choices=[('記事の内容が不適切である', '内容が不適切'), ('虚偽の内容が含まれている', '虚偽の内容'), ('タグの乱用をしている', 'タグの乱用'), ('プライバシーを侵害する内容である', 'プライバシー')], max_length=30, verbose_name='通報理由')),
                ('comment', models.CharField(max_length=2000, verbose_name='通報の詳細')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='通報した記事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='通報したユーザー')),
            ],
        ),
    ]
