# Generated by Django 4.2.7 on 2023-12-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, verbose_name='通報の詳細'),
        ),
    ]
