# Generated by Django 4.2.7 on 2023-12-25 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_follow_followers_alter_follow_follows'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goodarticle',
            unique_together={('article', 'user')},
        ),
    ]
