# Generated by Django 4.2.7 on 2023-12-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_notify_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='subject',
        ),
    ]
