# Generated by Django 4.2.7 on 2023-12-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_notify_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='subject',
            field=models.CharField(blank=True, default='ブログサイトから通知があります', max_length=20, null=True, verbose_name='件名'),
        ),
    ]
