# Generated by Django 4.2.7 on 2024-01-01 04:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_notify_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notify_Mail',
            new_name='NotifyMail',
        ),
    ]
