# Generated by Django 4.2.7 on 2024-01-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotifyMail',
        ),
    ]
